### ISSUE TITLE
This mod causes original hammer to double as well.

### ISSUE THREAD

**Issue by Voxel-Friend** [stfwi/engineers-tools#1]
As the title says. Tested with just IE and JEI, no doubling with hammer. with this mod, IE hammer doubles just like the one from this mod.

**Comment by stfwi** [comment]
Yepp, confirmed. Now the question is why. The recipe says ore and crushing hammer ...

**Comment by stfwi** [comment]
Ok, this was a tricky one. The oredict recipe system detects outputs, inputs and stuff that stays in the grafting grid. So no matter making it shaped with multiple ores, or JSON test did help here. The only solution I found without complete hammer GUI etc was to put one grit in the output, and the duplicated into the crafting grid. Then the recipe is not de-duplicated and does not overwrite the IE hammer crushing. booo.
