### ISSUE TITLE
[1.12.2] Ore Crushing Hammer doesn't lose durability when used to break blocks (e.g. Dirt)

### ISSUE THREAD

**Issue by Federsavo** [stfwi/engineers-tools#11]
^^

**Comment by stfwi** [comment]
Aye that's correct man ;-). Gonna make something up maybe this weekend to circumvent that. The tool has anyway the same harvest level as a squirrel on a stick. Maybe adding some funny think like a bit kockback when hitting a block (or entity) could be fun (and easy to code ;-) ).

**Comment by stfwi** [comment]
Good good, the hammer has still harvest level 0 (must have), but gets damaged when breaking a block with at least hardness 1. Checkout the knock-back stuff. When you hit villagers or animals you gently prod them away, when hitting aggressive mobs hard knock-back, also double click possible. The hammer loses durability when doing the latter.
Fun stuff ("muaaaahaha").
