### ISSUE TITLE
Fortune not work in 1.16.2

### ISSUE THREAD

**Issue by FierceManul** [stfwi/engineers-tools#12]
REDIA Tool's fortune not work in 1.16.2.
forge 33.0.37
[Thread-1/INFO] [wile.engineerstools.ModEngineersTools/]: Config file changed engineerstools-server.toml
[Thread-1/INFO] [wile.engineerstools.ModEngineersTools/]: Opt-outs:ariadne_coal_z,ariadne_coal_y,ariadne_coal_x
[Thread-1/INFO] [wile.engineerstools.ModEngineersTools/]: REDIA tool config: torch-placing, hoeing, tree-felling, safe-attack, durability:3000, initial-durability:100
[Thread-1/INFO] [wile.engineerstools.ModEngineersTools/]: REDIA tool efficiency curve: [0,1,1,2,2,3,3,3,3,4]
[Thread-1/INFO] [wile.engineerstools.ModEngineersTools/]: REDIA tool fortune curve: [0,0,0,0,1,1,1,1,2,3]
[Thread-1/INFO] [wile.engineerstools.ModEngineersTools/]: Stimpack config: uses:2, trigger:3.0 hearts, inst-heal:3.0 hearts.
[Thread-1/INFO] [wile.engineerstools.ModEngineersTools/]: Diving Capsule config: uses:10(dmg 10), trigger:3 bubbles, push:7 bubbles.
[Thread-1/INFO] [wile.engineerstools.ModEngineersTools/]: Musli Bar: hunger:6, saturation:1.2
[Thread-1/INFO] [wile.engineerstools.ModEngineersTools/]: Musli Press: storage:768hunger/512seeds, bar:8hunger/1seeds

**Comment by stfwi** [comment]
Hi, it does look ok in my testing grounds for 1.15 and all 1.16 versions. Double checked with gem ores etc.
Just to ensure, do you mean that it cannot be enchanted on an anvil with Fortune nor Efficiency, or that a Tool with Fortune does not drop more?

**Comment by FierceManul** [comment]
I mean the REDIA tool on high durability（no enchant）without fortune effect.
Is my operation wrong?

**Comment by stfwi** [comment]
You can repair the REDIA tool with diamonds directly in your crafting grid (without Anvil). If it is repaired, it will get Efficiency II. 
"Over-repair" again with a diamond, then it is Efficiency IV. After that Fortune I, etc.
So the trick with the tool is that you can get it early, and it also works for engineering packs where enchantments are disabled, but you must mechanically maintain the Tool (with diamonds) to keep the Efficiency and Fortune. Check it out.

**Comment by FierceManul** [comment]
ooohhh, I see!

**Comment by stfwi** [comment]
So, does this work on your machine (basically, can I close this issue ;) ) ?

**Comment by FierceManul** [comment]
Yes, it work!
