### ISSUE TITLE
[1.16.3] Unable to read the shift+ctrl help

### ISSUE THREAD

**Issue by ProsperCraft** [stfwi/engineers-tools#13]
![2020-10-01_17 41 50](https://user-images.githubusercontent.com/4427684/94873825-7e996480-040d-11eb-9055-c86ddd2999ca.png)

engineerstools-1.15.2-1.0.7

**Comment by stfwi** [comment]
Hi Goshen, ty for the hint. I am actually already aware of this thing, there is already a piece of code in the Forge to deal with text wrapping in tooltips, but it is currently still commented out with a note similar to "Needs checking if vanilla tooltips look exactly the same". 
So I did wait to prevent duplication of code. It's also the same in Engineer's Decor and G&S.

**Comment by stfwi** [comment]
Oky made some research at that point, there is no schedule yet for the `drawHoveringText()` implementation in Forge, so I gonna do a manual text-wrapping in the language file.

**Comment by stfwi** [comment]
Hi Goshen, the tooltips are now wrapped by the Forge, and I did also made a manual wrapping in the EN lang file before. Closing then. Cheers,-
