### ISSUE TITLE
(v1.1.2-b2) Engineer's Sleeping Bag still advances the day when used during the day.

### ISSUE THREAD

**Issue by ariosos** [stfwi/engineers-tools#15]
Steps to Reproduce:

1 - Craft the sleeping day.
2 - Make sure it's still day and press F3. Watch the local difficulty/day line on the debug screen.
3 - Spam right-click the sleeping bag on the floor.

Result:

The day will advance (even if it's during the daytime) despite the message saying "You can only sleep at night or during thunderstorms". (There is also rapid screen flashing, which might not be good for people affected by seizures).

Expected: The day should not advance.

**Comment by stfwi** [comment]
Hi, ty for the hint, gonna take a look what's happening there.

**Comment by stfwi** [comment]
Oky, was not a big deal in the code updating the "payer-sleeping-flag" obviously increments the day for whatever reason. I added a "is day" check around that. Update file is already up on Curse, cheers, -

**Comment by ariosos** [comment]
This fix partially works. if I click the sleeping bag once, it doesn't advance the day, but if I hold down the right mouse button on the ground for maybe 3-5 seconds, it'll advance the day.

**Comment by stfwi** [comment]
Hmm, seems then the day time update in the morning is delayed. Strange I did that on my local test server and did not see day advancing anymore. Are you using the mod in a big pack? (server/local?).

The only idea I have currently left is to add a cooldown timer for the item itself that prevents spam-click-usage, which is a bit hacky but will most likely do.

**Comment by ariosos** [comment]
> Hmm, seems then the day time update in the morning is delayed. Strange I did that on my local test server and did not see day advancing anymore. Are you using the mod in a big pack? (server/local?).
> 
> The only idea I have currently left is to add a cooldown timer for the item itself that prevents spam-click-usage, which is a bit hacky but will most likely do.

Yes, I'm using it in ATM6, which is laggy as it is...

**Comment by Gbergz** [comment]
This is still a thing, can advance days by just spamming the ground with the sleeping bag.

Using version: engineerstools-1.16.4-1.1.5

Here's a video: Check the day counter top right under minimap.
https://user-images.githubusercontent.com/26634554/116128210-fcce9880-a6c8-11eb-9a6f-83c4b871c82f.mp4

**Comment by stfwi** [comment]
Hi, cheers for the vid, I gonna double check for the next release (there are anyway a forge event for sleeping that I need to include there to allow other mods to hook into the can-sleep clause). Maybe this weekend'ish tackled. Cheers, -
