### ISSUE TITLE
Coarse Grit don't have smelting recipe in 1.16.4

### ISSUE THREAD

**Issue by Staegrin** [stfwi/engineers-tools#16]
Playing Direwolf20 1.16.4  
mod version engineerstools-1.16.4-1.1.2
Coarse Iron Grit and Coarse Gold Grit do not have smelting recipes.

**Comment by stfwi** [comment]
Hi, ty for the hint. Let me guess, you found the grit in a village chest, and Immersive Engineering (or another mod providing ore grit/dust) is installed? ;-)
(I disable the Coarse Grit in JEI and also its Ore Crushing recipes if any other mod already provides something comparable, that did also disable the smelting recipes. Since Coarse Grit can now be found in the Smith chest loot, smelting must be enabled again ...).
Fix is already up on Curse `engineerstools-1.16.4-1.1.3-b1`. Cheers!

**Comment by stfwi** [comment]
I made a quick test on my local server and SP, if you could double check on your machine if it works also for your setup would be cool (simply close the issue if ok). Cheers

**Comment by Staegrin** [comment]
updated to engineerstools-1.16.4-1.1.3-b1
![2020-12-26_03 42 30](https://user-images.githubusercontent.com/8494635/103144583-6a26e880-472c-11eb-875b-f3bf3731c022.png)
still won't smelt
![2020-12-26_03 43 05](https://user-images.githubusercontent.com/8494635/103144587-7ad75e80-472c-11eb-864d-bb2e568c2842.png)

**Comment by stfwi** [comment]
Hmm, have you added the mod yourself (I cannot imagine that Dire would add one of my mods)? Server or SP?

**Comment by Staegrin** [comment]
I added it myself/ I'm playing in single player. I've also checked the kubejs files to see if any recipe changes would affect these smelting recipes.

**Comment by stfwi** [comment]
Hi again, I just double checked if there was something in the code, the grit recipes are now really "condition-less" vanilla smelting recipes. Can you check again if there's some caching or some recipe reload functionality in the pack?

**Comment by Staegrin** [comment]
Did a new clean install of the direwolf20 1.16 pack added engineerstools-1.16.4-1.1.3-b1
Created a new world and still the Coarse Grits do not have smelting recipes.
![2020-12-27_20 23 31](https://user-images.githubusercontent.com/8494635/103178285-b0da2700-4881-11eb-9d32-63c43f0520e6.png)
![2020-12-27_20 23 38](https://user-images.githubusercontent.com/8494635/103178286-b20b5400-4881-11eb-808c-c03a80eca5d8.png)
the only mods that change recipes are kubejs. After deleting all of those scripts the smelting does finally work. Now I sadly have to go through all those scripts to figure out how they are removing a recipe for a mod not originally included in the modpack. Thanks for all the effort you put into this.
![2020-12-27_20 37 43](https://user-images.githubusercontent.com/8494635/103178485-6ce82180-4883-11eb-8561-9164a237dba1.png)

**Comment by stfwi** [comment]
Hmm ok. Maybe they added the mod in an early test phase and removed it then for some reason - it's a bigger pack, so there are likely already some mods that get players booted fast early game. Thanks for the feedback!

**Comment by Staegrin** [comment]
They put in a script to unify metals. Somehow this removed the recipe for Coarse Grit smelting without ever mentioning your mod

events.listen('recipes', event => {
    const { smelting, blasting } = event.recipes.minecraft

    var unifyMetal = function (name, hasOre, nuggetItem, ingotItem, blockItem, dustItem, gearItem, plateItem) {
        if (ingotItem !== '') event.replaceOutput('#forge:ingots/' + name, ingotItem)
        if (dustItem !== '') event.replaceOutput('#forge:dusts/' + name, dustItem)
        if (nuggetItem !== '') event.replaceOutput('#forge:nuggets/' + name, nuggetItem)
        if (blockItem !== '') event.replaceOutput('#forge:storage_blocks/' + name, blockItem)
        if (gearItem !== '') event.replaceOutput('#forge:gears/' + name, gearItem)
        if (plateItem !== '') event.replaceOutput('#forge:plates/' + name, plateItem)
        event.remove({output: '#forge:ingots/' + name, type: 'minecraft:smelting'})
        event.remove({output: '#forge:ingots/' + name, type: 'minecraft:blasting'})
        if (dustItem !== '' && ingotItem !== '') {
            smelting(ingotItem, '#forge:dusts/' + name).xp(0.7)
            blasting(ingotItem, '#forge:dusts/' + name).xp(0.7)
        }
        if (hasOre && ingotItem !== '') {
            smelting(ingotItem, '#forge:ores/' + name).xp(0.7)
            blasting(ingotItem, '#forge:ores/' + name).xp(0.7)
        }
    }

    unifyMetal('iron', true, 'minecraft:iron_nugget', 'minecraft:iron_ingot', 'minecraft:iron_block', 'thermal:iron_dust', 'thermal:iron_gear', 'thermal:iron_plate')
    unifyMetal('gold', true, 'minecraft:gold_nugget', 'minecraft:gold_ingot', 'minecraft:gold_block', 'thermal:gold_dust', 'thermal:gold_gear', 'thermal:gold_plate')

**Comment by stfwi** [comment]
K, ty for the info!

**Comment by Staegrin** [comment]
I just made my own script that runs later and adds back in the smelting recipe
```
events.listen('recipes', event => {
     event.smelting(Item.of('minecraft:gold_ingot', 1), 'engineerstools:gold_grit')
	 event.smelting(Item.of('minecraft:iron_ingot', 1), 'engineerstools:iron_grit')
})
```
