### ISSUE TITLE
[REQUEST] Basic steel tools and armor and more types of drill heads

### ISSUE THREAD

**Issue by Xorbah** [stfwi/engineers-tools#2]
Basically a broader use for steel ingots than what Immersive Engineering currently implements. Steel has a lot of uses but for some reason it could never be made into armor. Could you add this?

The second request is something i've already requested of you in the comments for Engineer's Tools on Curseforge - drill heads for immersive engineering in more varieties of metal (Such as copper, pig iron, mithril, etc) and if you need an example, Expanded Arcanum adds Thaumium and Void metal drillheads from Thaumcraft 6, whose repository can be found here - https://github.com/mallrat208/Expanded-Arcanum 

Let me know what you think. :)

**Comment by stfwi** [comment]
Hi - ya, IE has one armor similar to a chain mail, but no steel plate armor, agreed. I have an analog note on my todo/ideas sheet to dig into drill heads (I think this was due due the curse comment form you), so it's on the list.

I have to be honest according the "time frame" in which this can be done, it will take some time. I've even not started implementing the standard items I wanted to add to this mod, currently there is a lot ongoing with 1.13 ports etc.

I'll keep this open so it stays on screen.

**Comment by Xorbah** [comment]
This is fine. I just wanted to leave a footnote here as a suggestion so it
didn't get lost in the comments. Thank you for reading. :)

**Comment by stfwi** [comment]
Quick update - Blu is about to add steel armor to IE, so that should be already covered by now. With the drill heads ... I get more and more the impression that is really something for the IE core mod. It's quite a dependency thing (and therefore also stability/maintenance for ET). Need to discuss this with the IE devs, too.

**Comment by stfwi** [comment]
Ok, as IE is not yet on 1.14 I mark the issue as deferred -

**Comment by stfwi** [comment]
The current updates of IE indicate that these tools should be IE core matter, so I'll step away from that.
