### ISSUE TITLE
[Balance Consideration] Mindsqueezer takes set amount of xp points per squeeze rather than taking whole levels.

### ISSUE THREAD

**Issue by Darkmega18** [stfwi/engineers-tools#20]
This is a consideration for the squeezer. Currently it is possible to stockpile charged lapis, and then later when you have high levels make [stonks](https://wompampsupport.azureedge.net/fetchimage?siteId=7575&v=2&jpgQuality=100&width=700&url=https%3A%2F%2Fi.kym-cdn.com%2Fentries%2Ficons%2Foriginal%2F000%2F029%2F959%2FScreen_Shot_2019-06-05_at_1.26.32_PM.jpg) on your total xp amounts using other mechanics of xp storage from mods. Such as thermal expansion, enigmatic legacy and blood magic.

All of the above mods have xp storage that uses xp points. xp points per level increases exponentially after a certain point.

So using a charged lapis at level 5 might only give a few xp points. But storing up a lot of XP and eating them while you're already at 50 takes you to level 51 which is a considerable amount of xp regained... 
which can then be siphoned off into xp storage mediums at a great profit. To then be trickle fed back to the player to be consumed along with health back into charged lapis at a cheaper rate with less xp points cost per level.

Making each lapis maybe take roughly 100-200 points of xp out of you might be more balanced when cross modded compatibility is considered.

**Comment by stfwi** [comment]
I'll suspend/deprecate ET for 1.18. Some of the stuff will be moved to my little WilE's Collection mod. So closing this issue too, if I use the Charged Lapis I'll take your input into account ;) Cheers!
