### ISSUE TITLE
jei ingredient must not be empty (Exception in JEI opt-out processing: 'ingredients must not be empty.', skipping further JEI optout processing)

### ISSUE THREAD

**Issue by SDUBZ** [stfwi/engineers-tools#7]
Forge:1.14.4-111
ET:1.14.4-1.0.5-b1
JEI: 1.14.4-6.0.0.27
[latest.log](https://github.com/stfwi/engineers-tools/files/4021698/latest.log)

**Comment by stfwi** [comment]
Hi, is fixed in v1.0.5-b2, the version is not yet on curse because I could not test it yet. Should be uploaded in the next days. Thanks for keeping me in the loop!

**Comment by SDUBZ** [comment]
okay thank you

**Comment by stfwi** [comment]
Ok the version is up on curse. Could you double check if the issue is resolved for you and close?

**Comment by SDUBZ** [comment]
will do asap

**Comment by SDUBZ** [comment]
this issue has been fixed thank you for your work
