### ISSUE TITLE
[1.14.4] Crash when using sleeping bag.

### ISSUE THREAD

**Issue by Gbergz** [stfwi/engineers-tools#8]
MC-Version: **1.14.4**
Mod-Version: **1.0.5-b3**
Forge Version: **28.1.107**

**Crash-report:** [https://gist.github.com/Gbergz/78e9c3b3be08ca3bf0eb923d40d69012](https://gist.github.com/Gbergz/78e9c3b3be08ca3bf0eb923d40d69012)

Any ideas?

**Comment by stfwi** [comment]
Oh crash is not good. Not sure at the first glance what this is, but there seems to be a clash with my sleeping handler and the Botania Core sleeping hook.  The exception was raised there (`vazkii.botania.common.core.handler.SleepingHandler`), the question is if the ET mod did provoke the error beforehand. 
Please also inform Vazkii, it might also affect Botania.

**Comment by stfwi** [comment]
-> My PR for Botania was merged, so I think we can consider the issue here in the mod closed.
